junhok82/Algorithm_study

- DP/BOJ_1463/MBC_test.cpp
---
name: "[이니셜 출처 문제번호] Solving & Alternative"
title: "[이니셜 출처 문제번호] Solving (optional : & Alternative)"
---
* Issue : #1 
MBC_test
> [MBC BOJ 1463] Solving & Alternative

- DP/BOJ_2193/KJH.cpp
- DP/BOJ_2193/KJH_alternative.cpp
* Issue :  #2 
---
1) 현재 자리의 값이 0 일 경우 : 전 인덱스가 1이 나왔을 경우 + 전 인덱스가 0이 나왔을 경우
``` c++
dp[i][0] = dp[i-1][0] + dp[i-1][1];
```
2) 현재 자리의 값이 1일 경우  : 전 인덱스가 0이 나왔을 경우
``` c++
dp[i][1] = dp[i-1][0];
```
- 숫자를 나열해 보니, `1 1 2 3 5 8 13` 다음과 같은 규칙이 있었다.
> f(n) = f(n-1) + f(n-2)
먼저, 경우의 수를 이용해서 풀어보았다.
- 제출
------------
* 차이점
점화식을 이용해 풀어 보았다.
- 제출
> [KJH BOJ 2193] Solving & Alternative

- DP/BOJ_11726/KJH.cpp
- DP/BOJ_11726/KJH_alternative_limit_max_number.cpp
* Issue :  #3 
풀이 : https://junhok82.github.io/algorithm%20study/1%EC%A3%BC%EC%B0%A8-Offline/
> [KJH BOJ 11726] Solving & Alternative

- DP/BOJ_2579/KJH_Bottom_up.cpp
- DP/BOJ_2579/KJH_Top_Down.cpp
* Issue :  #14 
풀이 :  https://junhok82.github.io/algorithm%20study/2%EC%A3%BC%EC%B0%A8-%EB%AC%B8%EC%A0%9C/
> [KJH BOJ 2579] Solving & Alternative

- DP/BOJ_2579/KMJ_2579.cpp
---
name: "[KMJ_BOJ_2579] Solving"
about: Solving 
title: "[KMJ_BOJ_2579] Solving "
---
* Issue :  BOJ_2579
* 문제 풀이
1. 규칙 확인  
1) 계단은 한 칸 또는 두 칸을 오를 수 있다. 
2) 연속된 세칸을 밟을 수는 없다.
3) 마지막칸은 무조건 밟아야 한다.
2. 문제 접근
try. 1) 경우의 수를 나열 해보자.
---------------------------------------
3인경우
1 3 / 2 3
-------
4인경우
1 2 4 / 1 3 4 / 2 3 4 / 2 4
--------
5인경우
1 2 4 5 / 1 3 5 / 2 3 4 5 / 2 3 5
--------
6인경우
1 2 4 6 / 1 3 4 6 / 1 3 5 6
2 3 6 / 2 3 5 6 / 2 4 6
----------------------------------------
---> 나열 결과 일단 경우의 수를 구하는 문제가 아니라 이 방법은 맞는 방법이 아님을
깨달음. 하지만 마지막 숫자의 전 칸은 무조건 i-1칸 이던지 i-2칸이라는  것을 깨달음
try. 2) 점화식을 세워 보자.
경우의 수를 나열해보며 깨달은 규칙을 통해, 하나의 예시를 들어보았다.
예를 들어 7개 짜리 계단이 있다고 생각을 해보자.
7번째에 올라오기 위해서는 반드시 5번째나 6번째에서 올라왔을 것이다.
case 1) 5번째에서 올라왔을 경우 …
> [KMJ BOJ 2579] Solving

- DP/BOJ_2579/SSK.c
#16 
문제 접근
경우의 수로 접근함, 점화식의 문제의 경우 뒤늦게 깨달았으나 약속시간에 임박한 시간 부족으로인해
점화식으로 풀이는 하지 못함
경우의 수로 접근하되, 재귀함수를 사용
3개의 조건
1. 1~2계단
2. 3개 연속 계단 불가->1계단씩 오르는 것은 두번 사용 불가
3. 마지막 계단
연속된 계단의 갯수로는 변수 bindNum을 사용해 2 이상의 숫자는 카운트하지 않음
제한에서 계단의 갯수와 점수가 10000점을 넘어가지 않는 것에서 리턴 자료형은 int로 사용
-> 제출 결과 : 실패 (시간초과) , 경우에 수로 접근은 안되는 듯
> [SSK BOJ 2579] Solving & Alternative

- DP/BOJ_2579/2579_ClimbingStair.cpp
- DP/BOJ_2579/2579_ClimbingStair2.cpp
1. 계단은 한번에 한칸 또는 두칸씩 올라갈 수 있다.
2. 3칸 연속으로 올라갈 순 없다.
3. 마지막 계단은 반드시 밟아야 한다.
처음에 메모이제이션을 사용하여 점화식으로 접근하려 했지만 못했다.
그래서 의식의 흐름대로 풀었다.
1. 3번 규칙을 반드시 준수하기 위해 맨 뒤부터 시작.
2. 처음 인덱스을 더하고, N-2, N-1을 비교.
3. 둘 중 더 큰것을 sum에 더함.
이런식으로 풀었는데 결과적으로 실패.
반례가 있었는듯 싶다.
각설하고 이문제는 점화식으로 풀어야 하는 문제이다.
메모이제이션을 사용하여 각 인덱스에 해당하는 구간마다 최대값을 저장한다.
이후 맨 마지막 인덱스는 최대값을 갖게 되고 마지막 인덱스를 반환하는 식으로 접근해야한다.
최대값을 구할 때, 두가지 경우가 존재한다.
1.  해당 인덱스(N) + N-2까지의 합
2. 해당 인덱스(N) + 전 인덱스(N-2) + N-3까지의 합
1, 2를 비교하여 최대값을 갱신해 나아가게 된다.
결국 마지막 DP인덱스에서 최대값을 얻게 된다.
> [MBC BOJ 2579] Solving & Alternative

- DP/BOJ_1912/SSK_1912.cpp
---
name: "[이니셜 출처 문제번호] Solving & Alternative"
title: "[이니셜 출처 문제번호] Solving (optional : & Alternative)"
---
* Issue : #21 
> 1. n개의 정수로 이루어진 임의의 수열
> 2. 연속된 몇 개의 수를 선택 후, 가장 큰 합
1. 연속된 가장 큰 수  
> 연속된 숫자가 0보다 큰 숫자일 경우 더 할 수록 큰 숫자가 된다.  
```
10 -4 3 1 5 6 -35 12 21 -1
```
> 10 과 -4 를 더했을 경우 당장은 수가 작아지지만, 3,1,5,6까지 더했을 경우  
> 21로 더 큰 값을 구할 수 있다.   
> 같은 맥락으로 -35를 더할 경우 -24로 더한 값이 오히려 더 작아지기 때문에  
> 새로운 분기로 다시 최댓값을 구해준다.  
2. 최댓값 기억  
> 각 인덱스 당 최댓값들을 기억해준다.  
|index|0|1|2|3|4|5|6|7|8|9|
|----|---|---|---|---|---|---|---|---|---|---|
|origin|10|-4| 3| 1| 5| 6| -35| 12| 21| -1|
|add value|10|6|9|10|15|21|0|12|33|32|
|max|10|10|10|10|15|21|21|21|33|33|
> 실제 최댓값만 기억하면 되기 때문에 더해주는 …
> [SSK BOJ 1912] Solving  & Alternative

- DP/BOJ_1806/SSK.cpp
---
name: "[이니셜 출처 문제번호] Solving & Alternative"
title: "[이니셜 출처 문제번호] Solving (optional : & Alternative)"
---
* Issue : #22 
---
title: "BOJ_1806"  
excerpt: "10,000 이하의 자연수로 이루어진 길이 N짜리 수열이 주어진다. 이 수열에서 연속된 수들의 부분합 중에 그 합이 S 이상이 되는 것 중, 가장 짧은 것의 길이를 구하는 프로그램을 작성하시오."  
toc: true  
toc_sticky: true  
toc_label: ""  
categories:  
- algorithm_solving  
tags:  
- solving  
- cpp  
last_modified_at: 2019-12-06
---
Issue : <https://www.acmicpc.net/problem/1806>
- - -
- 길이가 N(100,000 이하), 합이 S(100,000,000)이 주어진다. -> int형으로 가능  
- 합중 가장 짧은 길이
(1) 가변의 길이를 하나씩 체크해야하는 문제기 때문에 투 포인터 알고리즘을 적용한다.
> 우선 포인터로 지정할 시작점과, 끝점을 0으로 초기화를 해준다.  
> **여기서 시작점과 끝점은 배열의 index를 의미한다.**
> 그리고 끝점이 N을 …
> [SSK BOJ 1806] Solving (update) 

- DP/BOJ_1806/MBC_BOJ_1806_ver1.cpp
- DP/BOJ_1806/MBC_BOJ_1806_ver2.cpp
---
name: "[이니셜 출처 문제번호] Solving & Alternative"
title: "[이니셜 출처 문제번호] Solving (optional : & Alternative)"
---
* Issue : #27 
1. 이분탐색으로 접근하자.
2. 탐색할 때 마다 left 부터 right값의 해당하는 데이터를 모두 더한다.
3. sum의 최대값을 계속 갱신
4. mid, mid+1을 스캔할 방법이 없으므로 따로 함수를 하나 생성하여 최소 길이를 구함
두 번째 방식은 투포인트 알고리즘을 사용해서 풀이했다.
> [MBC BOJ 1806] Solving & Alternative solving

- DP/BOJ_1912/KJH.cpp
- DP/BOJ_1912/KJH_split.cpp
* Issue :  #21 
풀이 : [BOJ 1912 풀이](https://junhok82.github.io/algorithm%20study/3%EC%A3%BC%EC%B0%A8-%EB%AC%B8%EC%A0%9C/)
> [KJH BOJ 1912] Solving & Alternative solving

- DP/BOJ_1806/KJH.cpp
- DP/BOJ_1806/KJH_Two_Point.cpp
* Issue :  #22 
풀이 : [BOJ 1806 풀이](https://junhok82.github.io/algorithm%20study/3%EC%A3%BC%EC%B0%A8-%EB%AC%B8%EC%A0%9C2/)
> [KJH BOJ 1806] Solving & Alternative solving

- DP/BOJ_2294/KJH.cpp
- DP/BOJ_2294/KJH_Top_down.cpp
* Issue :  #28 
풀이 : [BOJ 2294 풀이](https://junhok82.github.io/algorithm%20study/4%EC%A3%BC%EC%B0%A8-%EB%AC%B8%EC%A0%9C/)
> [KJH BOJ 2294] Solving & Alternative solving

- DP/BOJ_2294/SSK.cpp
- DP/BOJ_2294/SSK_alter.cpp
---
title: "BOJ_2294"  
excerpt: "가중치"  
toc: true  
toc_sticky: true  
toc_label: ""  
categories:  
- algorithm_solving  
tags:  
- solving  
- cpp  
last_modified_at: 2019-12-06
---
Issue : #28 
- - -
- 동전의 갯수 N(1<=n<=100), 가치의 합이 k(1<=s<=10,000)이 주어진다  
(같은 가치의 동전 여러번 주어질수 있다.)
- 같은 가치의 동전은 여러개 사용할 수 있다.  
- 동전의 가치는 100,000보다 작거나 같은 자연수  
- 합중 가장 짧은 갯수  
- 불가능 할때는 -1 return
(1) 입력시 제한 요소  
- 동전의 가치가 가치의 `k`보다 큰 10,000 이상의 동전은 사용할 수 있는 경우가 없다.  
- 동전이 중복으로 주어질 수 있다.
```cpp
if (coin_value[j] == temp || temp>k) { //중복 발생, k보다 클 때
n--;
i--;
check_value = true;
break;
} else if (k == temp) { //동전에서 k값과 동일할 때
printf("1");
return 0;
}
```
(2) dp를 만들어 동전의 가치에 따라 최소 동전갯수를 갱신해준다.
- 동전의 갯수만큼 반복
```cpp
dp[j] = min(dp[j], dp[j - coin_value[i]] + 1);
```
> **dp가 동전의 가치(coin_value) 값에 배수일 경우, 1씩 증가 …
> [SSK_BOJ_2294] Solving & Alternative

- DP/BOJ_2294/MBC_BOJ_2294.cpp
title: "BOJ_11055"
excerpt: "동전2"
Issue : https://www.acmicpc.net/problem/2294
issue : #39
> [MBC_BOJ_2294] Solving & Alternative

- DFS/BOJ_11724/KJH.cpp
> [KJH_BOJ_11724] Solving

- DFS/BOJ_11724/KJH.cpp
- DFS/BOJ_1743/KJH.cpp
> [KJH_BOJ_1743] Solving 

- DFS/BOJ_2667/MBC_BOJ_2667.cpp
---
name: "[MBC_BOJ_2667] Solving & Alternative"
title: "[MBC_BOJ_2667] Solving (optional : & Alternative)"
---
* Issue : #57
---
1. 배열에서의 영역들을 탐색하고 영역들의 크기를 구하면서 결과들을 오름차순으로 출력하는 문제.
2. dfs 또는 bfs를 사용해서 간단하게 영역의 크기를 구할 수 있음. (dfs사용)
3. sort()함수를 사용하여 오름차순 정렬.
4. result 벡터가 존재해야함.
- 제출
> [MBC_BOJ_2667] Solving & Alternative

- DFS/BOJ_1012/MBC_BOJ_1012.cpp
---
name: "[MBC_BOJ_1012] Solving & Alternative"
title: "[MBC_BOJ_1012] Solving (optional : & Alternative)"
---
* Issue : #56
---
1. 배열에서의 영역들의 개수를 구하는 문제.
2. dfs 또는 bfs를 사용해서 간단하게 component를 구할 수 있음.
3. 코드 보기 용이하게 class를 사용하여 구현.
- 제출
> [MBC_BOJ_1012] Solving & Alternative

- DFS/BOJ_2667/SSK.cpp
* Issue : #45 
[SSK_BOJ_2667](https://sekyushin.github.io/algorithm_solving/BOJ-2667/)
> [SSK_BOJ_2667] Solving &Alternaive

- DFS/BOJ_1743/SSK.cpp
#44 
[SSK_BOJ_1743](https://sekyushin.github.io/algorithm_solving/BOJ-1743/)
> [SSK_BOJ_1743] Solving &Alternaive

- DFS/BOJ_11724/SSK.cpp
#42 
[SSK_BOJ_11724](https://sekyushin.github.io/algorithm_solving/BOJ-11724/)
> [SSK_BOJ_11724]Solving &Alternative

- DFS/BOJ_1012/SSK.cpp
- DFS/BOJ_1012/SSK2.cpp
- issue : #43 
[SSK_BOJ_1012](https://sekyushin.github.io/algorithm_solving/BOJ-1012/)
> [SSK_BOJ_1012] Solving &Alternaive

- DFS/BOJ_2667/KJH.cpp
> [KJH_BOJ_2667] Solving

- DFS/BOJ_11403/SSK.cpp
- DFS/BOJ_9466/SSK(fail).cpp
- DFS/BOJ_9466/SSK.cpp
- DFS/PROGRAMMERS_49994/SSK_1.cpp
- DFS/PROGRAMMERS_49994/SSK_2.cpp
* Issue : #58 
---
[프로그래머스 49994 방문길이 풀이](https://sekyushin.github.io/algorithm_solving/PROGRAMMERS-49994/)
[BOJ_9466 - 텀 프로젝트](https://sekyushin.github.io/algorithm_solving/BOJ-9466/)
[BOJ_11403 - 경로 찾기](https://sekyushin.github.io/algorithm_solving/BOJ-11403/)
> [SSK_7]Solving & Alternative

- DFS/BOJ_11403/MBC_BOJ_11403.cpp
- DFS/BOJ_9466/MBC_BOJ_9466_ver1.cpp
- DFS/BOJ_9466/MBC_BOJ_9466_ver2.cpp
- DFS/PROGRAMMERS_49994/MBC_PROGRAMMERS_49994.cpp
---
name: "[MBC_7] Solving & Alternative"
title: "[MBC_7] Solving & Alternative"
---
#61
[BOJ 9466](https://minbyeongchan.github.io/category/Algorithm/9466)
[BOJ 11403](https://minbyeongchan.github.io/category/Algorithm/11403)
[PROGRAMMERS](https://minbyeongchan.github.io/category/Algorithm/PROGRAMMERS_49994)
> [MBC_7] Solving & Alternative

- DFS/BOJ_11403/KJH.cpp
- DFS/BOJ_9466/KJH.cpp
- DFS/PROGRAMMERS_49994/KJH.cpp
> [KJH_7] Solving
